language: php

branches:
  only:
    - master

dist: trusty

sudo: false

php:
  - 7.2
  - 7.3

env:
  global:
    - DEFAULT=1
    - CODECOVERAGE=0
    - PHPCS=0

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: PHPSTAN=1 DEFAULT=0
    - php: 7.2
      env: CODECOVERAGE=1 DEFAULT=0

script:
  - if [[ $DEFAULT = 1 ]]; then phpunit; fi
  - if [[ $CODECOVERAGE = 1 ]]; then phpunit --coverage-clover=coverage.xml; fi
  - if [[ $PHPSTAN = 1 ]]; then composer require "composer/ca-bundle:^1.0" && composer require --dev "phpstan/phpstan:^0.10" && vendor/bin/phpstan analyse -c phpstan.neon -l max src; fi

after_success:
  - if [[ $CODECOVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

before_script:
  - composer install
